<a href="https://colab.research.google.com/github/Bibhukalyan/simple_RNN/blob/main/embadings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

#

In [2]:
# sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
# Define the vocabulary
voc_size = 10000
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[9561, 7640, 2868, 9628], [9561, 7640, 2868, 8609], [9561, 6517, 2868, 3479], [5232, 515, 1046, 5006, 8197], [5232, 515, 1046, 5006, 1037], [8727, 9561, 3667, 2868, 2868], [5360, 3187, 1924, 5006]]


In [4]:
# Word embeding representation
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9561 7640 2868 9628]
 [   0    0    0    0 9561 7640 2868 8609]
 [   0    0    0    0 9561 6517 2868 3479]
 [   0    0    0 5232  515 1046 5006 8197]
 [   0    0    0 5232  515 1046 5006 1037]
 [   0    0    0 8727 9561 3667 2868 2868]
 [   0    0    0    0 5360 3187 1924 5006]]


In [6]:
#feature representation
dim = 10 #10 is the number of featues that is used, we are telling use 10 features
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step


array([[[ 1.46141909e-02,  4.86564748e-02, -1.71800703e-03,
         -3.77158746e-02,  9.20990855e-03, -1.51442364e-03,
         -3.69654670e-02, -2.50821710e-02, -1.42507665e-02,
         -1.57482252e-02],
        [ 1.46141909e-02,  4.86564748e-02, -1.71800703e-03,
         -3.77158746e-02,  9.20990855e-03, -1.51442364e-03,
         -3.69654670e-02, -2.50821710e-02, -1.42507665e-02,
         -1.57482252e-02],
        [ 1.46141909e-02,  4.86564748e-02, -1.71800703e-03,
         -3.77158746e-02,  9.20990855e-03, -1.51442364e-03,
         -3.69654670e-02, -2.50821710e-02, -1.42507665e-02,
         -1.57482252e-02],
        [ 1.46141909e-02,  4.86564748e-02, -1.71800703e-03,
         -3.77158746e-02,  9.20990855e-03, -1.51442364e-03,
         -3.69654670e-02, -2.50821710e-02, -1.42507665e-02,
         -1.57482252e-02],
        [-4.73373644e-02,  2.53400952e-03, -3.83748524e-02,
         -1.64665096e-02,  4.75477427e-04, -5.29431179e-03,
          6.53759390e-03, -4.69657034e-03,  3.643684

In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (7, 8, 10)                  │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)